name: flutter_practice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  persistent_bottom_nav_bar: ^5.0.2
  intl: ^0.18.0
  khalti_flutter: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.0.0
  flutter_translate: ^4.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/



